---
- name: import rpm key
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: copy elasticsearch repository file
  template: src=elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=644

- name: install elasticsearch
  yum: name=elasticsearch-{{ es_version }} state=present

- name: start elasticsearch
  service: name=elasticsearch state=started enabled=yes
